// SPDX-License-Identifier: AGPL-3.0-only

//! Noticing that a newer build exists, from a source that can be authenticated.
//!
//! Replaces `update_check.rs`, which asked the GitHub API for the `beta`
//! release's `target_commitish` and compared it to `build_commit()`. That could
//! only ever say *different*, never *newer* -- a git SHA has no order -- and it
//! authenticated nothing: whoever answered the request decided what the user was
//! told. It also polled `api.github.com`, which is rate limited to sixty
//! requests an hour per address, so one makerspace behind one NAT broke it for
//! everyone there, silently, because failure here is deliberately silence.
//!
//! # What this module is
//!
//! Checking, fetching and verifying: the manifest, its signature, the key list
//! and its epochs, the anti-rollback floor, and the payload download with its
//! digest. Putting a verified file in place is [`apply`], which is where every
//! platform difference lives.
//!
//! Four things here had to be right in the *first* shipped binary because they
//! cannot be retrofitted onto copies already in the field: the key list and its
//! epochs, the anti-rollback floor and which number space it lives in, unknown
//! manifest keys being ignored rather than rejected, and `requires_reinstall`.
//!
//! # Two number spaces, and they must never be compared to each other
//!
//! - **`build`** counts CI runs. `1000 + github.run_number`, stamped by
//!   `release.yml`, read back by [`crate::app::build_number`]. It identifies a
//!   *payload*.
//! - **`seq`** counts manifests. Generated by `scripts/sign-release.sh`, which
//!   refuses to sign unless it strictly increases. It identifies a *release
//!   decision*.
//!
//! They diverge by construction the moment a rollback happens: publishing a
//! manifest with `seq + 1` naming an older `build` is how a bad release is
//! walked back. So the anti-rollback floor is compared **only** against `seq`,
//! and `minimum_build` **only** against `build`. Mixing them warns the whole
//! fleet or none of it, and on a fresh install it would set a floor of 1005
//! against a `seq` counter that starts at 1 -- silently refusing every manifest
//! that will ever be published.
//!
//! # Verify, then parse
//!
//! `key_epoch` is a manifest field, so choosing the key by reading it means
//! parsing attacker bytes to decide which key says whether they are attacker
//! bytes. The order here is: decode the signature container, try each compiled-in
//! key until one verifies, keep the epoch **from our own key list**, and only
//! then parse. See [`verify_manifest`].

use std::fmt;

/// Putting a verified file in place, on all three platforms. See the module.
pub mod apply;

/// The keys that may sign a manifest, each with the epoch it *is* -- never the
/// epoch of its position in this slice.
///
/// **Append only, and the numbers do not close up.** The epoch is a field rather
/// than an index because this list shrinks as well as grows: recovering from a
/// leak means shipping a build that DROPS the compromised key and appends a
/// fresh standby, and dropping index 0 would renumber everything after it. A
/// client that had persisted `floor_epoch = 1` would then refuse the very build
/// sent to rescue it. After a rotation this list reads `&[(1, STANDBY),
/// (2, FRESH)]` -- no epoch 0, and no ambiguity about which key that is.
///
/// Generated 2026-08-30 on Thomas's machine with `minisign -G`. Epoch 0 is the
/// live key (id `B6D059FAFC11CF4C`); epoch 1 is the standby (id
/// `BDB38C17AB97C0FD`), whose secret half is held off the build machine so a
/// leak of the live key has a recovery path. **Where** it is held is recorded in
/// `handoff.md` and deliberately not here: this file is public, and a public
/// file naming the two places a signing key is backed up turns a document into
/// a target list. SECURITY.md describes the rotation mechanism without the
/// locations, which is the part a reader actually needs.
///
/// Only the public halves are here, which is the
/// whole point: a compiled-in public key is the only root of trust available,
/// because there is no Apple Developer ID and no Authenticode certificate to
/// make the operating system vouch for anything.
const TRUSTED_KEYS: &[(u32, &str)] = &[
    (0, "RWRMzxH8+lnQtk8qdxGmcdtqvNehqg9aNbBOS93i8EnPzycE+6wBvZeJ"),
    (1, "RWT9wJerF4yzvRVZh7HQcd4eHrwx6z5bMU9LQB2mdrhqFPf10K6PthPw"),
];

/// Where a payload may be fetched from, compiled in rather than supplied by the
/// manifest.
///
/// **This is what bounds a leaked key.** The manifest names a *filename* and
/// never a URL, so an attacker holding the signing key can sign a manifest and
/// still cannot serve one: they would also need write access to a GitHub release
/// they do not control. Two independent things must fail, and even then the
/// worst outcome is a downgrade to one of our own previously published builds,
/// because every digest they sign still has to match bytes we published.
const DOWNLOAD_PREFIX: &str = "https://github.com/MakerViking/brokkrsculpt/releases/download/beta/";

/// The absolute ceiling on a payload, compiled in and enforced **first**.
///
/// The signed `size` is a *secondary tightening* applied after the signature
/// verifies. Using the declared size as the only cap would let anyone who can
/// answer the request make us stream gigabytes into the user's directory before
/// the digest check fails. `MAX_THUMB_BYTES` in `articles.rs` is the precedent,
/// and it is the right one precisely because it is a constant the far end
/// cannot set.
const MAX_UPDATE_BYTES: u64 = 128 * 1024 * 1024;

/// The manifest and its signature, as plain release-download URLs rather than
/// API calls. Asset URLs go through the CDN with no rate limit; the API poll
/// this replaces had sixty an hour per address.
const MANIFEST_URL: &str =
    "https://github.com/MakerViking/brokkrsculpt/releases/download/beta/latest.conf";
const SIGNATURE_URL: &str =
    "https://github.com/MakerViking/brokkrsculpt/releases/download/beta/latest.conf.minisig";

/// Absolute caps on the two things fetched before anything is trusted.
///
/// Compiled in, and enforced before the signature is checked, because at that
/// point every byte is attacker controlled. A manifest is a few hundred bytes
/// and a signature is two lines; these are three orders of magnitude of slack.
const MAX_MANIFEST_BYTES: u64 = 64 * 1024;
const MAX_SIGNATURE_BYTES: u64 = 4 * 1024;

/// Structural caps inside the manifest. A line count as well as a byte count,
/// because 64 KiB of one-character lines is a different denial of service from
/// 64 KiB of one line.
const MAX_MANIFEST_LINES: usize = 200;
const MAX_FIELD_BYTES: usize = 256;

/// The largest ordinal a manifest may claim.
///
/// Bounds a poisoned floor: the floor advances on a successful apply, so an
/// attacker holding the key could otherwise sign an enormous `seq` over a
/// genuinely published payload and leave every client that took it with a floor
/// no honest release will ever clear.
///
/// An absolute constant rather than a comparison against the running build,
/// which an earlier draft specified: that mixes the two number spaces. It cannot
/// be relative to the floor either, because a fresh install seeds `floor_seq = 0`
/// and is the *most* exposed. At the measured cadence -- four releases in one
/// afternoon -- a million is well over a century.
const MAX_SEQ: u64 = 1_000_000;

/// The platform this binary would look for in a manifest.
///
/// `None` on anything else, which means the updater is inert there rather than
/// guessing. The strings match the `slug` values in `release.yml`'s matrix.
const fn platform_slug() -> Option<&'static str> {
    if cfg!(all(target_os = "linux", target_arch = "x86_64")) {
        Some("linux-x86_64")
    } else if cfg!(all(target_os = "windows", target_arch = "x86_64")) {
        Some("windows-x86_64")
    } else if cfg!(all(target_os = "macos", target_arch = "aarch64")) {
        Some("macos-arm64")
    } else {
        None
    }
}

/// One platform's payload, as the manifest describes it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Payload {
    /// A bare filename. Never a URL, and validated by [`valid_payload_name`].
    pub name: String,
    /// Bytes, exactly. A secondary tightening applied *after* the signature
    /// verifies -- the absolute cap is what protects the download itself.
    pub size: u64,
    /// Lowercase hex, 64 characters, already syntax-checked.
    pub sha256: String,
}

/// A manifest that has been verified and then parsed, in that order.
///
/// Construction is only possible through [`verify_manifest`], which is the point:
/// there is no way to hold one of these that did not come from bytes a compiled-in
/// key signed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Manifest {
    /// Manifest space. Compared against the persisted floor, never against a build.
    pub seq: u64,
    /// Build space. The ordinal of the payload this manifest offers.
    pub build: u64,
    /// Which key signed it, cross-checked against the key that actually verified.
    pub key_epoch: u32,
    /// Build space. A running build strictly below this gets a stronger warning.
    pub minimum_build: u64,
    /// Whether this build can be reached by replacing one executable.
    pub requires_reinstall: bool,
    /// This platform's payload, if the manifest names one. Absent means "no
    /// update for this platform", which is an ordinary outcome and not an error.
    pub payload: Option<Payload>,
}

/// Why an offer was refused.
///
/// **Every one of these is a named rejection**, never a default and never a
/// saturating fallback. These are attacker-controlled bytes at a point where
/// nothing is trusted yet, and "the field was missing so we used zero" is how a
/// manifest with no `minimum_build` silently disables a warning.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Refusal {
    /// This build was not stamped by the release pipeline, is dirty, or is
    /// running out of a `target/` directory. The updater is inert.
    NotAReleaseBuild,
    /// No platform payload could apply here.
    UnsupportedPlatform,
    /// The network did not answer, or answered with a status.
    Unreachable(String),
    /// Larger than a compiled-in cap, before anything was trusted.
    TooLarge { what: &'static str, cap: u64 },
    /// The signature file was not valid UTF-8, or minisign could not parse it.
    MalformedSignature(String),
    /// No trusted key verified it. Covers a wrong key, a tampered manifest and a
    /// legacy `Ed` signature alike -- all of them mean the same thing to a user.
    NotSignedByUs(String),
    /// A required field was absent, unparseable, duplicated, or too long.
    BadField(String),
    /// The manifest declared an epoch that is not the one that signed it. Not an
    /// attack: a release-night mistake, which would otherwise persist a
    /// `floor_epoch` no key can satisfy again.
    EpochDisagrees { declared: u32, signed_by: u32 },
    /// Older than this install has already accepted.
    BelowFloor { seq: u64, floor: u64 },
    /// Signed by a key this install has already superseded.
    EpochBelowFloor { epoch: u32, floor: u32 },
    /// Implausible ordinal; see [`MAX_SEQ`].
    SeqImplausible(u64),
    /// The payload was not the length the signed manifest declared. Named
    /// separately from a digest mismatch because the two mean different things
    /// to a user: this one is usually a truncated download.
    PayloadSizeMismatch { declared: u64, actual: u64 },
    /// The payload's SHA-256 did not match the signed one. Nothing is made
    /// executable on this path.
    DigestMismatch { expected: String, actual: String },
    /// This install cannot replace itself here, with the reason. Covers a
    /// system install, a directory other users can write, and a filesystem that
    /// said no -- all of which mean "update it the way you installed it".
    CannotReplace(String),
    /// Another copy of the application holds the update lock.
    AlreadyUpdating,
    /// This copy downloads and hands over rather than replacing itself.
    ///
    /// Three ways to get here: `BROKKR_NO_SELF_UPDATE=1`; a `.app` bundle on a
    /// platform with no whole-bundle path, since editing one in place would
    /// leave a half-swapped application; and any future platform with no
    /// replacement of its own.
    HandOverOnly,
    /// The staged file vanished between writing it and installing it. On
    /// Windows that means an antivirus quarantined it, which retrying cannot
    /// fix -- a self-rewriting `.exe` is a textbook Defender heuristic, so
    /// deletion is at least as likely as a sharing violation.
    ///
    Quarantined,
}

impl fmt::Display for Refusal {
    /// Worded for a status line, because there is no terminal to read anything
    /// else in. A refusal the user cannot act on still says which number was
    /// wrong -- a silent permanent refusal is indistinguishable from a network
    /// that stopped answering.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotAReleaseBuild => write!(f, "this build does not update itself"),
            Self::UnsupportedPlatform => write!(f, "no update is published for this platform"),
            Self::Unreachable(why) => write!(f, "could not check for updates ({why})"),
            Self::TooLarge { what, cap } => write!(f, "the {what} was larger than {cap} bytes"),
            Self::MalformedSignature(why) => write!(f, "the update signature is malformed ({why})"),
            Self::NotSignedByUs(why) => {
                write!(f, "the update was not signed by BrokkrSculpt ({why})")
            }
            Self::BadField(why) => write!(f, "the update manifest is malformed ({why})"),
            Self::EpochDisagrees { declared, signed_by } => {
                write!(f, "the update names key {declared} but was signed by key {signed_by}")
            }
            Self::BelowFloor { seq, floor } => {
                write!(f, "ignoring update {seq}: this install has already accepted {floor}")
            }
            Self::EpochBelowFloor { epoch, floor } => {
                write!(f, "ignoring an update signed by key {epoch}: this install requires {floor}")
            }
            Self::SeqImplausible(seq) => {
                write!(f, "the update claims an implausible number ({seq})")
            }
            Self::PayloadSizeMismatch { declared, actual } => {
                write!(f, "the download was {actual} bytes, not the {declared} it should be")
            }
            Self::DigestMismatch { .. } => {
                write!(f, "the download did not match its signature and was discarded")
            }
            Self::CannotReplace(why) => write!(f, "this copy cannot update itself: {why}"),
            Self::AlreadyUpdating => {
                write!(f, "another copy of BrokkrSculpt is installing an update")
            }
            Self::HandOverOnly => write!(
                f,
                "this copy cannot install updates itself -- the download has been verified and \
                 saved, and replacing the application is a manual step"
            ),
            Self::Quarantined => write!(
                f,
                "the downloaded update was removed before it could be installed, most likely by \
                 antivirus -- nothing was changed"
            ),
        }
    }
}

/// The anti-rollback floor this install has written for itself.
///
/// Seeded at **zero** on a fresh install -- see the module header. It advances
/// only on a successful apply, never on merely seeing an offer, so an attacker
/// who can show a client a manifest cannot move its floor by doing so.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Floor {
    pub epoch: u32,
    pub seq: u64,
}

/// Verify a manifest's signature, then parse it. In that order, and the order is
/// the entire point of this function.
///
/// # Why the key is found by trying rather than by reading an id
///
/// minisign signatures carry the 8-byte id of the key that made them, and
/// `PublicKey::verify` compares it as its first statement -- before the Blake2b
/// prehash and before Ed25519. But `minisign-verify` 0.2.5 exposes no accessor
/// for it: `key_id` is private on both `Signature` and `PublicKey`. So selection
/// is a loop over [`TRUSTED_KEYS`], and it is cheap for exactly that reason: a
/// wrong key costs one base64 decode and one integer compare, not a signature
/// check. Against a two-entry list that is nothing.
///
/// The epoch is taken from the entry that verified, never from its position, and
/// the parsed `key_epoch` must then agree with it.
///
/// # Neither comment is ever read
///
/// `untrusted_comment` is unsigned, so it is straightforwardly attacker text.
/// `trusted_comment` is the trap, because it *does* verify -- the global
/// signature covers `signature || trusted_comment`. Verified is not validated:
/// none of the caps or named rejections below reach it, and reading it would
/// create a second channel of meaning running beside the manifest with nothing
/// binding the two together. A trusted comment saying `build:1018` next to a
/// manifest saying `build:1012` is a state no code here would notice.
pub fn verify_manifest(body: &[u8], signature: &[u8]) -> Result<Manifest, Refusal> {
    if body.len() as u64 > MAX_MANIFEST_BYTES {
        return Err(Refusal::TooLarge { what: "update manifest", cap: MAX_MANIFEST_BYTES });
    }
    if signature.len() as u64 > MAX_SIGNATURE_BYTES {
        return Err(Refusal::TooLarge { what: "update signature", cap: MAX_SIGNATURE_BYTES });
    }

    // `Signature::decode` takes `&str`, so the bytes off the wire get a UTF-8
    // check here and a non-UTF-8 `.minisig` is a named rejection rather than a
    // panic somewhere later.
    let signature = std::str::from_utf8(signature)
        .map_err(|why| Refusal::MalformedSignature(why.to_string()))?;
    let decoded = minisign_verify::Signature::decode(signature)
        .map_err(|why| Refusal::MalformedSignature(why.to_string()))?;

    let mut last_error = String::from("no trusted key was tried");
    let mut signed_by = None;
    for (epoch, encoded) in TRUSTED_KEYS {
        let key = match minisign_verify::PublicKey::from_base64(encoded) {
            Ok(key) => key,
            // A malformed entry in our own compiled-in list. Not reachable
            // without a code change, and not a reason to trust anything else.
            Err(why) => {
                last_error = why.to_string();
                continue;
            }
        };
        // `false` is `allow_legacy`. A legacy `Ed` signature fails here with
        // `UnexpectedAlgorithm`; `UnsupportedLegacyMode` is what `verify_stream`
        // returns and we do not call it, because the manifest is small and is
        // verified in one shot.
        match key.verify(body, &decoded, false) {
            Ok(()) => {
                signed_by = Some(*epoch);
                break;
            }
            Err(why) => last_error = why.to_string(),
        }
    }
    let Some(signed_by) = signed_by else {
        return Err(Refusal::NotSignedByUs(last_error));
    };

    // Only now are these bytes worth parsing.
    let text = std::str::from_utf8(body)
        .map_err(|why| Refusal::BadField(format!("not valid UTF-8: {why}")))?;
    let manifest = parse_manifest(text, signed_by)?;

    if manifest.key_epoch != signed_by {
        return Err(Refusal::EpochDisagrees { declared: manifest.key_epoch, signed_by });
    }
    if manifest.seq > MAX_SEQ {
        return Err(Refusal::SeqImplausible(manifest.seq));
    }
    Ok(manifest)
}

/// Parse a manifest that has already been verified.
///
/// Separate from [`verify_manifest`] only so the caller cannot accidentally
/// invoke it on unverified bytes -- it is private, and the public entry point
/// verifies first.
///
/// **Unknown keys are ignored, not rejected**, and that is a v1 format decision
/// with no retrofit. Rejecting them means the format can never gain a field
/// without breaking every client already in the field, and the remedy would have
/// to travel down the channel the mistake is in. It costs nothing here because
/// the manifest is signed as a whole: nothing can smuggle meaning into a field
/// no code reads, and the fields that *are* read are each validated by name.
///
/// **Duplicate keys ARE rejected.** `paths::entries` yields them happily and a
/// last-wins collect would let a manifest carry two `build` lines and have the
/// client and a human reading the file disagree about which one counts.
fn parse_manifest(text: &str, _signed_by: u32) -> Result<Manifest, Refusal> {
    if text.lines().count() > MAX_MANIFEST_LINES {
        return Err(Refusal::BadField(format!("more than {MAX_MANIFEST_LINES} lines")));
    }

    let mut fields: Vec<(&str, &str)> = Vec::new();
    for (key, value) in crate::paths::entries(text) {
        if key.len() > MAX_FIELD_BYTES || value.len() > MAX_FIELD_BYTES {
            return Err(Refusal::BadField(format!(
                "`{key}` is longer than {MAX_FIELD_BYTES} bytes"
            )));
        }
        if fields.iter().any(|(seen, _)| *seen == key) {
            return Err(Refusal::BadField(format!("`{key}` appears twice")));
        }
        fields.push((key, value));
    }
    let get = |name: &str| fields.iter().find(|(key, _)| *key == name).map(|(_, value)| *value);

    // Every required field is fetched the same way: absent is an error, and
    // unparseable is a *different* error naming the field. Neither is a default.
    let number = |name: &str| -> Result<u64, Refusal> {
        let raw = get(name).ok_or_else(|| Refusal::BadField(format!("`{name}` is missing")))?;
        raw.parse::<u64>()
            .map_err(|_| Refusal::BadField(format!("`{name}` is not a number: {raw:?}")))
    };

    let seq = number("seq")?;
    let build = number("build")?;
    let minimum_build = number("minimum_build")?;
    let key_epoch = u32::try_from(number("key_epoch")?)
        .map_err(|_| Refusal::BadField("`key_epoch` is out of range".into()))?;
    // Required rather than optional-defaulting-to-zero, for the same reason as
    // `minimum_build`: a field that silently disables itself when omitted is
    // discovered on the release where it mattered.
    let requires_reinstall = match number("requires_reinstall")? {
        0 => false,
        1 => true,
        other => {
            return Err(Refusal::BadField(format!(
                "`requires_reinstall` must be 0 or 1, not {other}"
            )));
        }
    };

    // An absent platform block means "no update for this platform". An absent
    // *field* inside a block that exists is malformed, which is a different
    // thing and gets a different answer.
    let payload = match platform_slug() {
        None => None,
        Some(slug) => {
            let name_key = format!("{slug}.name");
            match get(&name_key) {
                None => None,
                Some(name) => {
                    if !valid_payload_name(name) {
                        return Err(Refusal::BadField(format!(
                            "`{name_key}` is not a plain filename: {name:?}"
                        )));
                    }
                    let size = number(&format!("{slug}.size"))?;
                    let sha_key = format!("{slug}.sha256");
                    let sha256 = get(&sha_key)
                        .ok_or_else(|| Refusal::BadField(format!("`{sha_key}` is missing")))?;
                    if sha256.len() != 64 || !sha256.bytes().all(|b| b.is_ascii_hexdigit()) {
                        return Err(Refusal::BadField(format!("`{sha_key}` is not 64 hex digits")));
                    }
                    Some(Payload {
                        name: name.to_string(),
                        size,
                        sha256: sha256.to_ascii_lowercase(),
                    })
                }
            }
        }
    };

    Ok(Manifest { seq, build, key_epoch, minimum_build, requires_reinstall, payload })
}

/// Whether a manifest-supplied name is a plain filename and nothing else.
///
/// The URL is built by concatenating [`DOWNLOAD_PREFIX`] with this, so anything
/// that could climb out of that prefix -- a slash, a backslash, a `..`, a scheme
/// -- has to be refused here or the compiled-in prefix stops bounding anything.
/// An allowlist rather than a denylist, because the set of characters that are
/// safe is small and knowable and the set that is dangerous is neither.
fn valid_payload_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= MAX_FIELD_BYTES
        && name != ".."
        && !name.contains("..")
        && name.bytes().all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'_' | b'-'))
}

/// Whether a verified manifest may be acted on by this install, given its floor.
///
/// Separate from verification because it answers a different question.
/// Verification asks *who signed this*; this asks *may they still*. A leaked key
/// stays compiled in until a new binary ships, so its signatures go on verifying
/// for ever -- this is what refuses them.
pub fn admissible(manifest: &Manifest, floor: Floor) -> Result<(), Refusal> {
    if manifest.key_epoch < floor.epoch {
        return Err(Refusal::EpochBelowFloor { epoch: manifest.key_epoch, floor: floor.epoch });
    }
    // Only compared within the same epoch. A higher epoch that verifies is a
    // rotation, and a rotation resets the seq floor to zero -- the epoch bump is
    // itself the anti-rollback guarantee from that point, since `floor_epoch`
    // has advanced and nothing below it will ever verify again.
    if manifest.key_epoch == floor.epoch && manifest.seq <= floor.seq {
        return Err(Refusal::BelowFloor { seq: manifest.seq, floor: floor.seq });
    }
    Ok(())
}

/// What `--version` prints, as a string so it can be tested.
///
/// `main.rs` is the crate root of a binary-only crate, so nothing in it is
/// reachable from a unit test. The formatting therefore lives here and `main`
/// only prints it -- which matters because CI greps this output for the build
/// ordinal, and a change to the wording would break the release pipeline with
/// no test anywhere objecting.
///
/// Flat `key = value`, the same shape `paths::entries` parses, so this output,
/// the signed manifest, `update.conf` and `update.state` all read alike.
pub fn version_report() -> String {
    let build = match crate::app::build_number() {
        Some(build) => build.to_string(),
        // `none`, never `0`. A stamp that failed to parse must not compare as a
        // number: `grep -qx "build = 0"` succeeding on a broken build is exactly
        // the false green the readback exists to prevent.
        None => "none".to_string(),
    };
    format!(
        "version = {}\nbuild = {}\ncommit = {}\n",
        env!("CARGO_PKG_VERSION"),
        build,
        crate::app::build_commit()
    )
}

/// The URL a verified payload is fetched from.
///
/// Built here and nowhere else, so the compiled-in prefix is the only thing that
/// can ever decide the host. The name has already been through
/// [`valid_payload_name`] by the time a [`Payload`] exists.
pub fn payload_url(payload: &Payload) -> String {
    format!("{DOWNLOAD_PREFIX}{}", payload.name)
}

/// Stream `reader` into `sink`, checking the length and the digest as it goes.
///
/// **The absolute cap is applied before the signed size, not instead of it.**
/// A body is bounded by [`MAX_UPDATE_BYTES`] first and by `payload.size`
/// second; using the declared size as the only bound would let anyone who can
/// answer the request make us stream gigabytes into the user's directory before
/// the digest failed. The digest is computed over exactly the bytes written, so
/// there is no window between "verified" and "used" -- what is checked is what
/// lands.
///
/// SHA-256 from `ring`, which is already compiled as rustls' backend. Hand
/// rolling it here is forbidden: this is the check that decides whether network
/// bytes get the execute bit.
pub fn check_payload(
    mut reader: impl std::io::Read,
    payload: &Payload,
    sink: &mut impl std::io::Write,
) -> Result<(), Refusal> {
    if payload.size > MAX_UPDATE_BYTES {
        return Err(Refusal::TooLarge { what: "update payload", cap: MAX_UPDATE_BYTES });
    }
    let mut context = ring::digest::Context::new(&ring::digest::SHA256);
    let mut written: u64 = 0;
    let mut buffer = [0u8; 64 * 1024];
    loop {
        let read = reader.read(&mut buffer).map_err(|why| Refusal::Unreachable(why.to_string()))?;
        if read == 0 {
            break;
        }
        // Refused the moment it exceeds rather than after buffering the rest,
        // so an over-long body costs one chunk of slack and no more.
        written += read as u64;
        if written > payload.size {
            return Err(Refusal::PayloadSizeMismatch { declared: payload.size, actual: written });
        }
        context.update(&buffer[..read]);
        sink.write_all(&buffer[..read]).map_err(|why| Refusal::Unreachable(why.to_string()))?;
    }
    // Short is as wrong as long. The digest would catch a truncated download
    // anyway; naming the length properly means a network fault reports as one
    // rather than as a digest mismatch, which reads like tampering.
    if written != payload.size {
        return Err(Refusal::PayloadSizeMismatch { declared: payload.size, actual: written });
    }
    let digest = context.finish();
    let actual: String = digest.as_ref().iter().map(|byte| format!("{byte:02x}")).collect();
    // Constant time is not needed: the expected digest came out of a manifest
    // that has already been authenticated, so there is no secret here to leak.
    if actual != payload.sha256 {
        return Err(Refusal::DigestMismatch { expected: payload.sha256.clone(), actual });
    }
    Ok(())
}

/// Whether the running build is one the manifest marks as known-bad.
///
/// **Strictly below**, so a client *at* the minimum meets it and is left alone,
/// which is what the name says. In build space against the running ordinal,
/// never against `seq`: after a rollback the two have diverged by construction.
pub fn below_minimum(manifest: &Manifest, running: u64) -> bool {
    running < manifest.minimum_build
}

/// What the interface is told, once everything above has agreed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Offer {
    /// The ordinal being offered. May be **lower** than the running build: a
    /// rollback publishes a higher `seq` naming an older `build`, and the UI
    /// must not call that an upgrade.
    pub build: u64,
    /// The ordinal actually running, so the message can name both.
    pub running: u64,
    /// The running build is below `minimum_build`. Shown even when the user has
    /// skipped this build: "not now" answers an offer, not a warning.
    pub known_bad: bool,
    /// This build cannot be reached by replacing one executable, so the user is
    /// sent to the release page rather than offered an in-place update.
    pub requires_reinstall: bool,
    /// The payload this platform would download, carried through from the
    /// verified manifest so accepting the offer needs no second fetch -- and,
    /// more importantly, so the bytes that get downloaded are described by the
    /// same signed manifest that was checked, not by a later one that might
    /// have changed underneath.
    ///
    /// `None` when the manifest names no payload for this platform, which is an
    /// ordinary outcome: the offer is still worth showing, it just cannot be
    /// acted on here.
    pub payload: Option<Payload>,
    /// The manifest's own counter, carried so a successful apply can raise the
    /// anti-rollback floor to it. **Manifest space, never build space.**
    pub seq: u64,
    /// Which key signed the manifest this offer came from, for the same reason.
    pub key_epoch: u32,
}

impl Offer {
    /// Worded without claiming a direction unless one is known.
    pub fn headline(&self) -> String {
        if self.known_bad {
            format!("build {} has a known problem; build {} fixes it", self.running, self.build)
        } else if self.build > self.running {
            format!("Build {} is out — you are on {}", self.build, self.running)
        } else {
            format!("Build {} is being republished — you are on {}", self.build, self.running)
        }
    }
}

/// When the check may run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum When {
    /// Never. The packager kill switch also lands here.
    Never,
    /// Only while the welcome screen is up, alongside the articles.
    Welcome,
    /// Every launch. **The default**, settled 2026-08-30: it matches what the
    /// old unconditional check did and adds a switch where there was none, and
    /// the person who most needs to hear their build is stale is the one who
    /// turned the welcome screen off.
    #[default]
    Always,
}

/// `update.conf`, as read from the config directory.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Settings {
    pub when: When,
    /// A build the user said "not now" to. A *newer* one still offers -- which
    /// is the thing SindriCAD lacks, where declining is not remembered and the
    /// modal returns eight seconds into every session.
    pub skip_build: Option<u64>,
}

/// The packager kill switch, Zed's pattern. Set it and the whole update surface
/// is replaced by the packager's text -- and the **check does not run either**, a
/// distro build that keeps polling GitHub to display nothing being a connection
/// nobody asked for and nobody can see.
const EXPLANATION_VARIABLE: &str = "BROKKR_UPDATE_EXPLANATION";

/// Parse `update.conf`. Lenient in the house style of `printer.rs` and
/// `spacemouse.rs`: this is the user's own file, not attacker bytes, so an
/// unreadable value falls back to the default rather than refusing to launch.
pub fn settings_from(text: &str) -> Settings {
    let mut settings = Settings::default();
    for (key, value) in crate::paths::entries(text) {
        match key {
            "check_for_updates" => {
                settings.when = match value {
                    "never" => When::Never,
                    "welcome" => When::Welcome,
                    "always" => When::Always,
                    _ => settings.when,
                }
            }
            "skip_build" => settings.skip_build = value.parse().ok(),
            _ => {}
        }
    }
    settings
}

/// Read `update.conf`, or the defaults if there is none.
pub fn settings() -> Settings {
    if std::env::var_os(EXPLANATION_VARIABLE).is_some() {
        return Settings { when: When::Never, skip_build: None };
    }
    crate::paths::config_file("update.conf")
        .and_then(|path| std::fs::read_to_string(path).ok())
        .map_or_else(Settings::default, |text| settings_from(&text))
}

/// Render settings back to the file's text.
///
/// Split from the write so it can be tested without a path, which is the shape
/// `printer.rs`, `welcome.rs` and `crash.rs` all use -- `paths.rs` reads the
/// environment at call time and the suite runs in parallel, so a test that wrote
/// through the real path would reach into the config of whoever ran it.
pub fn settings_text(settings: &Settings) -> String {
    let when = match settings.when {
        When::Never => "never",
        When::Welcome => "welcome",
        When::Always => "always",
    };
    let mut text = format!(
        "# BrokkrSculpt update checks.\n\
         # never   -- do not check at all\n\
         # welcome -- only while the welcome screen is up\n\
         # always  -- every launch (the default)\n\
         check_for_updates = {when}\n"
    );
    if let Some(build) = settings.skip_build {
        // A build the user declined. A NEWER one still offers; this is not a
        // permanent off switch, and the comment says so because the next person
        // to read this file will otherwise assume it is one.
        text.push_str(&format!(
            "# A build that was declined. A newer one is still offered.\n\
             skip_build = {build}\n"
        ));
    }
    text
}

/// Remember the answer. A write that fails is dropped, like `welcome.rs`: the
/// preference is worth less than the session, and there is nothing useful to say
/// about a read-only config directory in the middle of a click.
pub fn store(settings: &Settings) {
    let Some(path) = crate::paths::config_file("update.conf") else {
        return;
    };
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, settings_text(settings));
}

/// Parse `update.state`.
///
/// Absent, unreadable or malformed all give the same answer: a zero floor. That
/// is the documented reset -- "delete `update.state`" -- and it must therefore
/// be a *recoverable* state rather than a refusal, because the user performing
/// it has no terminal to read an error in.
pub fn floor_from(text: &str) -> Floor {
    let mut floor = Floor::default();
    for (key, value) in crate::paths::entries(text) {
        match key {
            "floor_epoch" => floor.epoch = value.parse().unwrap_or(0),
            "floor_seq" => floor.seq = value.parse().unwrap_or(0),
            _ => {}
        }
    }
    floor
}

/// Remember the digest of the build being replaced, so the revert can refuse to
/// run whatever happens to be sitting at `.old`.
///
/// Written beside the floor in `update.state`. A failure is dropped rather than
/// aborting the update: the consequence is that a revert will refuse for want of
/// a digest, which is the safe direction.
pub fn record_previous(sha256: &str) {
    record_state(Some(sha256), None, None);
}

/// Rewrite `update.state`, preserving what is not being changed.
///
/// One writer for the whole file, because a read-modify-write per field would
/// let two of them race and drop each other's line. Everything here is under the
/// `update.lock` in practice; this is the shape that makes that lock sufficient.
fn record_state(previous: Option<&str>, installed: Option<u64>, checked: Option<u64>) {
    let Some(path) = crate::paths::state_file("update.state") else {
        return;
    };
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let keep = |name: &str| {
        crate::paths::entries(&existing)
            .find(|(key, _)| *key == name)
            .map(|(_, value)| value.to_string())
    };
    let floor = floor();
    let previous = previous.map(str::to_string).or_else(|| keep("previous_sha256"));
    let installed = installed.map(|n| n.to_string()).or_else(|| keep("installed_build"));
    let checked = checked.map(|n| n.to_string()).or_else(|| keep("last_check"));

    let mut text = format!("floor_epoch = {}\nfloor_seq = {}\n", floor.epoch, floor.seq);
    if let Some(previous) = previous {
        text.push_str(&format!("previous_sha256 = {previous}\n"));
    }
    if let Some(installed) = installed {
        // Machine readable, and deliberately NOT `last_outcome`: that one is
        // prose for the About panel and must not quietly become a flag.
        text.push_str(&format!("installed_build = {installed}\n"));
    }
    if let Some(checked) = checked {
        text.push_str(&format!("last_check = {checked}\n"));
    }
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, text);
}

/// Record a successful apply: raise the floor, and remember what was installed.
///
/// **The floor advances here and nowhere else.** Not on merely seeing an offer,
/// which is what stops someone who can show a client a manifest from moving its
/// floor by doing so — and not never, which is what an earlier revision did.
/// The first real update on this machine installed correctly and left
/// `floor_seq = 0`, so the install would have accepted an older manifest
/// afterwards. Nothing in the suite caught it, because every test drove the
/// pure functions rather than the apply path.
///
/// `installed_build` is written in the same breath because the crash-driven
/// revert offer compares the running ordinal against it, and an absent value
/// silently means "never offer".
pub fn record_applied(seq: u64, key_epoch: u32, build: u64) {
    let Some(path) = crate::paths::state_file("update.state") else {
        return;
    };
    let existing = std::fs::read_to_string(&path).unwrap_or_default();
    let keep = |name: &str| {
        crate::paths::entries(&existing)
            .find(|(key, _)| *key == name)
            .map(|(_, value)| value.to_string())
    };
    let mut text =
        format!("floor_epoch = {key_epoch}\nfloor_seq = {seq}\ninstalled_build = {build}\n");
    if let Some(previous) = keep("previous_sha256") {
        text.push_str(&format!("previous_sha256 = {previous}\n"));
    }
    if let Some(checked) = keep("last_check") {
        text.push_str(&format!("last_check = {checked}\n"));
    }
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(path, text);
}

/// Note that a check succeeded, for freshness only.
///
/// **The only clock value this design stores, and it is displayed rather than
/// compared against any rule.** That is the whole difference from the `expires`
/// field this plan rejected: a stale `last_check` produces a line in the Help
/// panel, never a refusal, so a machine with a wrong clock loses a sentence and
/// not its updates.
pub fn record_check_succeeded() {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|since| since.as_secs())
        .unwrap_or_default();
    record_state(None, None, Some(now));
}

/// One line for the diagnostics and the About panel: what the updater is set
/// to, what it last installed, and how fresh the last successful check is.
pub fn outcome_line() -> String {
    let settings = settings();
    let when = match settings.when {
        When::Never => "off",
        When::Welcome => "with the welcome screen",
        When::Always => "on",
    };
    let installed = installed_build()
        .map_or_else(|| "never self-updated".to_string(), |n| format!("installed build {n}"));
    let skipped = settings.skip_build.map_or_else(String::new, |n| format!(", skipping {n}"));
    format!("{when}, {installed}{skipped}, {}", freshness_line())
}

/// The ordinal this install last put in place, if any.
///
/// Read from `installed_build` rather than from `last_outcome`: that one is
/// prose for the About panel and must not quietly become a machine-readable
/// flag, because the day someone reworded it the comparison would start
/// failing silently.
pub fn installed_build() -> Option<u64> {
    let text = crate::paths::state_file("update.state")
        .and_then(|path| std::fs::read_to_string(path).ok())?;
    crate::paths::entries(&text)
        .find(|(key, _)| *key == "installed_build")
        .and_then(|(_, value)| value.parse().ok())
}

/// The Help panel's one line about update freshness.
///
/// Read once at startup and not refreshed, so a check that succeeds during this
/// session does not change it until the next launch. That is a deliberate
/// trade -- it changes once a day and re-reading a file per frame to say so
/// would be absurd -- but it means a first run reads "no update check has
/// succeeded yet" for the whole session even after one has.
pub fn freshness_line() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|since| since.as_secs())
        .unwrap_or_default();
    let text = crate::paths::state_file("update.state")
        .and_then(|path| std::fs::read_to_string(path).ok())
        .unwrap_or_default();
    match days_since_check(&text, now) {
        None => "no update check has succeeded yet".to_string(),
        Some(0) => "checked for updates today".to_string(),
        Some(1) => "last update check: yesterday".to_string(),
        Some(days) => format!("last update check: {days} days ago"),
    }
}

/// How long since a check last succeeded, in whole days.
///
/// `None` when none ever has, or when the stored value is in the future --
/// which a wrong clock can produce, and which must read as "unknown" rather
/// than as a negative number of days.
pub fn days_since_check(text: &str, now: u64) -> Option<u64> {
    let last: u64 = crate::paths::entries(text)
        .find(|(key, _)| *key == "last_check")
        .and_then(|(_, value)| value.parse().ok())?;
    now.checked_sub(last).map(|seconds| seconds / 86_400)
}

/// The digest recorded before the last apply, if there is one.
pub fn previous_sha256_from(text: &str) -> Option<String> {
    crate::paths::entries(text)
        .find(|(key, _)| *key == "previous_sha256")
        .map(|(_, value)| value.to_string())
}

/// Read the persisted floor.
pub fn floor() -> Floor {
    crate::paths::state_file("update.state")
        .and_then(|path| std::fs::read_to_string(path).ok())
        .map_or_else(Floor::default, |text| floor_from(&text))
}

/// How many redirects to follow. GitHub currently uses exactly one.
const MAX_REDIRECTS: usize = 3;

/// Named so a proxy log on someone's own network says who is calling. GitHub
/// also refuses a request with no user agent.
const USER_AGENT: &str = "BrokkrSculpt";

/// Long enough for two small files on a bad line, short enough that nothing the
/// user is doing waits on it. Only ever applied to the manifest and its
/// signature, both capped in the tens of kilobytes -- the payload download in
/// Phase 2 must NOT reuse this, because a wall-clock budget over 33 MB fails
/// every connection under about 13 Mbit/s, permanently and silently.
const META_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(20);

/// Whether a redirect may be followed to this host.
///
/// **`github.com` is an equality test and not a suffix**, because
/// `evilgithub.com` ends with `github.com`. The leading dot on the other arm
/// does the same work: `evil-githubusercontent.com` does not end with
/// `.githubusercontent.com`.
///
/// Measured 2026-08-30, the real chain is one hop from `github.com` to
/// `release-assets.githubusercontent.com` -- **not** `objects.githubusercontent.com`,
/// which is where GitHub used to send these. Naming a single host here would
/// have refused every download on every install, unfixable through the channel
/// it broke, so the rule is by suffix on that domain.
fn host_is_allowed(host: &str) -> bool {
    if !host.is_ascii() {
        return false;
    }
    let host = host.to_ascii_lowercase();
    host == "github.com" || host.ends_with(".githubusercontent.com")
}

/// The host part of an absolute https URL, if it has one.
fn host_of(url: &str) -> Option<&str> {
    let rest = url.strip_prefix("https://")?;
    let end = rest.find(['/', '?', '#']).unwrap_or(rest.len());
    let authority = &rest[..end];
    // No credentials in the authority: `https://github.com@evil.example/` has a
    // host of `evil.example`, and a naive prefix test would read it as GitHub.
    if authority.contains('@') {
        return None;
    }
    let host = authority.split(':').next()?;
    (!host.is_empty()).then_some(host)
}

/// GET a small file, following redirects by hand.
///
/// Nothing stores the redirect target. GitHub's 302 lands on a signed URL good
/// for about an hour, so a cached one is a bug with a one-hour fuse: green in
/// every test, failing the first time someone leaves a dialog open over lunch.
/// Follow redirects by hand and hand back the response, ready to read.
///
/// **By hand, because the obvious mechanism silently does not work.** ureq's
/// middleware hook wraps `run()` and the redirect loop lives *inside* `run()`,
/// so a middleware allowlist would see the first request and no other while
/// looking entirely correct. `max_redirects(0)` returns the 3xx as an ordinary
/// response instead, so the host can be checked on every hop -- and each hop
/// being its own call is also what makes `https_only` bite per hop rather than
/// once.
///
/// Nothing stores the redirect target: it is a signed URL good for about an
/// hour, so a cached one is a bug with a one-hour fuse.
fn follow_to_body(
    agent: &ureq::Agent,
    url: &str,
    what: &'static str,
) -> Result<ureq::http::Response<ureq::Body>, Refusal> {
    let mut current = url.to_string();
    for _ in 0..=MAX_REDIRECTS {
        match host_of(&current) {
            Some(host) if host_is_allowed(host) => {}
            _ => return Err(Refusal::Unreachable(format!("refused to follow {what} off GitHub"))),
        }
        let response = agent
            .get(&current)
            .header("User-Agent", USER_AGENT)
            .call()
            .map_err(|why| Refusal::Unreachable(why.to_string()))?;

        let status = response.status().as_u16();
        if (300..400).contains(&status) {
            let location = response
                .headers()
                .get("location")
                .and_then(|value| value.to_str().ok())
                .ok_or_else(|| Refusal::Unreachable("a redirect with no location".into()))?;
            // Absolute only. A relative redirect is legal HTTP and GitHub does
            // not send one; resolving it would mean writing a URL joiner, and a
            // wrong one here re-opens exactly the hole the allowlist closes.
            if !location.starts_with("https://") {
                return Err(Refusal::Unreachable("a redirect that was not absolute https".into()));
            }
            current = location.to_string();
            continue;
        }
        return Ok(response);
    }
    Err(Refusal::Unreachable(format!("{what} redirected more than {MAX_REDIRECTS} times")))
}

/// GET a small file whole, under an absolute cap.
fn get_capped(
    agent: &ureq::Agent,
    url: &str,
    cap: u64,
    what: &'static str,
) -> Result<Vec<u8>, Refusal> {
    use std::io::Read;

    let mut response = follow_to_body(agent, url, what)?;
    // `as_reader()` is NOT used: it carries a hidden 10 MiB cap that would
    // surface as a network-looking error rather than as a size refusal.
    let mut body = Vec::new();
    response
        .body_mut()
        .with_config()
        .limit(cap + 1)
        .reader()
        .take(cap + 1)
        .read_to_end(&mut body)
        .map_err(|why| Refusal::Unreachable(why.to_string()))?;
    if body.len() as u64 > cap {
        return Err(Refusal::TooLarge { what, cap });
    }
    Ok(body)
}

/// The whole check, start to finish. Blocking: call it off the interface thread.
///
/// Returns `Ok(None)` for "nothing to say", which is the common case and is not
/// an error. Every refusal is named so the caller can decide what is worth a
/// status line -- most are not.
pub fn check(
    running: Option<u64>,
    settings: &Settings,
    floor: Floor,
) -> Result<Option<Offer>, Refusal> {
    // **The updater is structurally inert on anything but a release build.**
    // `None` covers a local build, a source build and a failed stamp; the dirty
    // and unknown checks are free and they are the difference between "inert"
    // and "one keypress away from overwriting the developer's own binary".
    let running = running.ok_or(Refusal::NotAReleaseBuild)?;
    let commit = crate::app::build_commit();
    if commit == "unknown" || commit.ends_with("-dirty") {
        return Err(Refusal::NotAReleaseBuild);
    }
    if settings.when == When::Never {
        return Ok(None);
    }
    if platform_slug().is_none() {
        return Err(Refusal::UnsupportedPlatform);
    }

    let agent: ureq::Agent = ureq::Agent::config_builder()
        .timeout_global(Some(META_TIMEOUT))
        // ureq's default is `false`, so without this a redirect to plain http
        // is followed -- and these URLs do redirect.
        .https_only(true)
        // Followed by hand instead; see `get_capped`.
        .max_redirects(0)
        .build()
        .into();

    let body = get_capped(&agent, MANIFEST_URL, MAX_MANIFEST_BYTES, "update manifest")?;
    let signature = get_capped(&agent, SIGNATURE_URL, MAX_SIGNATURE_BYTES, "update signature")?;

    let manifest = verify_manifest(&body, &signature)?;
    // Recorded on a successful FETCH AND VERIFY, before the floor is consulted:
    // an offer refused by the floor still proves the channel is answering, and
    // that is the only thing this value is for.
    record_check_succeeded();
    admissible(&manifest, floor)?;

    let known_bad = below_minimum(&manifest, running);
    // The offer is suppressed by `skip_build`; the warning is not. "Not now" is
    // an answer to an offer and not to "the build you are on is broken".
    if !known_bad && (manifest.build == running || Some(manifest.build) == settings.skip_build) {
        return Ok(None);
    }
    Ok(Some(Offer {
        build: manifest.build,
        running,
        known_bad,
        requires_reinstall: manifest.requires_reinstall,
        payload: manifest.payload,
        seq: manifest.seq,
        key_epoch: manifest.key_epoch,
    }))
}

/// Where a downloaded payload is put.
///
/// The state directory, not `/tmp`: a cross-filesystem rename degrades to a
/// copy, and copy-over-a-running-image is precisely the operation that fails on
/// both Linux and Windows. Phase 3 replaces in place from here, so getting the
/// filesystem right now costs nothing and saves a rewrite.
pub fn download_directory() -> Option<std::path::PathBuf> {
    crate::paths::state_file("updates")
}

/// Fetch the offered payload, verify it, and leave it on disk.
///
/// **This is the whole of Phase 2, and it deliberately stops here.** Nothing is
/// made executable, nothing is replaced and nothing restarts. It is the
/// permanent macOS answer -- where the unit of replacement is a signed bundle
/// and editing one can turn a working install into an unlaunchable one -- and
/// the interim answer everywhere else.
///
/// Returns where the file landed, so the caller can tell the user. A user who
/// is handed a verified file and not told where it is has been given nothing.
pub fn download(offer: &Offer, into: &std::path::Path) -> Result<std::path::PathBuf, Refusal> {
    let payload = offer.payload.as_ref().ok_or(Refusal::UnsupportedPlatform)?;
    // **Which directory is a correctness question, not a tidiness one.**
    // `install` finishes with `rename(staged, target)`, and a cross-filesystem
    // rename degrades to a copy -- which is precisely the operation that fails
    // against a running image. So an install stages beside the binary and a
    // hand-over stages in the state directory, and the caller picks.
    let directory = into.to_path_buf();
    std::fs::create_dir_all(&directory)
        .map_err(|why| Refusal::Unreachable(format!("could not make {directory:?} ({why})")))?;

    // **A separate agent from the manifest's, and it sets no wall-clock limit.**
    // `timeout_global` covers the body, so 20 s over a 33 MB payload demands
    // 13.4 Mbit/s sustained and fails every slower connection for ever, in
    // silence. `timeout_recv_body` is a rolling stall timer rather than a
    // deadline -- it is recomputed on every read poll -- so a slow line is
    // allowed to finish while a dead socket is not. `timeout_recv_response` is
    // deliberately unset: it is also checked while reading the body, so setting
    // it would silently cap the download.
    let agent: ureq::Agent = ureq::Agent::config_builder()
        .timeout_resolve(Some(std::time::Duration::from_secs(10)))
        .timeout_connect(Some(std::time::Duration::from_secs(10)))
        .timeout_send_request(Some(std::time::Duration::from_secs(20)))
        .timeout_recv_body(Some(std::time::Duration::from_secs(30)))
        .https_only(true)
        .max_redirects(0)
        .build()
        .into();

    // Every attempt starts at byte zero and re-derives its URL. The 302 lands
    // on a signed URL good for about an hour, so a stored one is a bug with a
    // one-hour fuse: green in every test, failing the first time someone leaves
    // the dialog open over lunch.
    let url = payload_url(payload);
    let mut response = follow_to_body(&agent, &url, "update payload")?;

    // Into a `.part` first, created `O_EXCL` at 0600 and `O_NOFOLLOW`, so a
    // failed or refused download never leaves something at the final path that
    // looks complete, unverified bytes are never world-readable while they are
    // being written, and a symlink planted at that name is never followed.
    let (partial, mut file) = apply::stage_in(&directory, &payload.name)?;
    let final_path = directory.join(&payload.name);

    let outcome = check_payload(
        response.body_mut().with_config().limit(MAX_UPDATE_BYTES).reader(),
        payload,
        &mut file,
    );
    if let Err(why) = outcome {
        // Nothing verified is left lying about under a name suggesting it was.
        drop(file);
        let _ = std::fs::remove_file(&partial);
        return Err(why);
    }
    // Executable and flushed only AFTER the digest matched. Creating it 0755 and
    // then filling it with unverified network bytes would invert the point of
    // staging it private in the first place, and `~/.local/bin` is on `PATH` on
    // most distributions.
    apply::finish_staging(&file)?;
    drop(file);
    std::fs::rename(&partial, &final_path).map_err(|why| {
        let _ = std::fs::remove_file(&partial);
        Refusal::Unreachable(format!("could not finish the download ({why})"))
    })?;
    Ok(final_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real fixtures, generated 2026-08-30 with `minisign -G -W` (no
    /// passphrase -- these are throwaway TEST keys and their secret halves are
    /// not in this repository or anywhere else). Signed over [`BODY`] exactly.
    const TEST_PUB: &str = "RWS9DRS2PjPJFCEmYkM5+oD0NrhANS4KSaGrkRC+SCskQyS5yUZl8hnj";
    const OTHER_PUB: &str = "RWT0Fd4hGFCYMmHKUG0lQfT/3f5zDPVwQYfN9kOzNbfEyo2knSpZadxr";

    const BODY: &str = "seq = 7\nbuild = 1018\nkey_epoch = 0\nminimum_build = 1012\nrequires_reinstall = 0\nlinux-x86_64.name = brokkrsculpt-1018-linux-x86_64\nlinux-x86_64.size = 33543336\nlinux-x86_64.sha256 = 0000000000000000000000000000000000000000000000000000000000000000\n";

    const SIG: &str = "untrusted comment: signature from minisign secret key\nRUS9DRS2PjPJFFDxP1xB2R6SlRfnapvzszEQwjB3w/HittVj8WxPZfxEIlaJoFOkAkIVQPpUyMvoX20O2lbl75+KBEZgHnIE/A8=\ntrusted comment: timestamp:1788046770\tfile:latest.conf\thashed\nHgY02wiFKYshDuHXS8HCaUv54syTzux9FuSJ8/MbiqaKCtWAcJwjMa1Y67J+crHyoZYcgtUGvbx7lsaH5av1CA==\n";

    /// The same manifest signed by a DIFFERENT key.
    const SIG_OTHER_KEY: &str = "untrusted comment: signature from minisign secret key\nRUT0Fd4hGFCYMpuH2Zvk/PQBl2QICBejA4E4SmjKDpTNwGkO63RDx1qKLkSntLuhZiUu1dPgpEI3cPuy/wboAJqHQw7kxTnOygI=\ntrusted comment: timestamp:1788046770\tfile:latest.conf\thashed\nMnv61qZnnmFIiW8XW4zfAPmD8Z8Ykpv7MOTdGG6IP11G1iks6sOXd3V/7RvHfjQ28hFSmTkhSzNvNn5ImcgZCQ==\n";

    /// [`SIG`] with its algorithm bytes changed from `ED` (prehashed) to `Ed`
    /// (legacy). Built by hand, because **minisign 0.12 cannot produce a legacy
    /// signature at all** -- it prehashes with or without `-H`, which is worth
    /// knowing because the plan warned that the tool default was legacy. That
    /// was true of older minisign and is not true of what is installed.
    const SIG_LEGACY_ALGORITHM: &str = "untrusted comment: signature from minisign secret key\nRWS9DRS2PjPJFFDxP1xB2R6SlRfnapvzszEQwjB3w/HittVj8WxPZfxEIlaJoFOkAkIVQPpUyMvoX20O2lbl75+KBEZgHnIE/A8=\ntrusted comment: timestamp:1788046770\tfile:latest.conf\thashed\nHgY02wiFKYshDuHXS8HCaUv54syTzux9FuSJ8/MbiqaKCtWAcJwjMa1Y67J+crHyoZYcgtUGvbx7lsaH5av1CA==\n";

    /// Verify against the test key rather than the shipped ones, so these tests
    /// exercise the real code path without the production keys' secret halves
    /// existing anywhere a test could reach.
    fn verify_with(keys: &[(u32, &str)], body: &[u8], sig: &[u8]) -> Result<Manifest, Refusal> {
        let signature =
            std::str::from_utf8(sig).map_err(|why| Refusal::MalformedSignature(why.to_string()))?;
        let decoded = minisign_verify::Signature::decode(signature)
            .map_err(|why| Refusal::MalformedSignature(why.to_string()))?;
        let mut last = String::new();
        let mut signed_by = None;
        for (epoch, encoded) in keys {
            let Ok(key) = minisign_verify::PublicKey::from_base64(encoded) else { continue };
            match key.verify(body, &decoded, false) {
                Ok(()) => {
                    signed_by = Some(*epoch);
                    break;
                }
                Err(why) => last = why.to_string(),
            }
        }
        let signed_by = signed_by.ok_or(Refusal::NotSignedByUs(last))?;
        let text = std::str::from_utf8(body).map_err(|_| Refusal::BadField("utf8".into()))?;
        let manifest = parse_manifest(text, signed_by)?;
        if manifest.key_epoch != signed_by {
            return Err(Refusal::EpochDisagrees { declared: manifest.key_epoch, signed_by });
        }
        if manifest.seq > MAX_SEQ {
            return Err(Refusal::SeqImplausible(manifest.seq));
        }
        Ok(manifest)
    }

    /// The shipped keys must be the real ones and must parse. A placeholder that
    /// reached a release would make every install permanently unreachable.
    #[test]
    fn the_compiled_in_keys_are_real_and_parse() {
        assert_eq!(TRUSTED_KEYS.len(), 2, "a live key and a standby, per the plan");
        for (epoch, encoded) in TRUSTED_KEYS {
            assert!(
                minisign_verify::PublicKey::from_base64(encoded).is_ok(),
                "epoch {epoch} is not a usable minisign public key"
            );
            assert!(!encoded.contains("PLACEHOLDER"), "epoch {epoch} is a placeholder");
        }
        assert_eq!(TRUSTED_KEYS[0].0, 0);
        assert_eq!(TRUSTED_KEYS[1].0, 1, "the standby is epoch 1, not index 1");
    }

    #[test]
    fn a_genuine_manifest_verifies_and_parses() {
        let manifest = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes())
            .expect("the fixture is signed by the test key");
        assert_eq!(manifest.seq, 7);
        assert_eq!(manifest.build, 1018);
        assert_eq!(manifest.key_epoch, 0);
        assert_eq!(manifest.minimum_build, 1012);
        assert!(!manifest.requires_reinstall);
        // Two different number spaces, and the fixture keeps them different on
        // purpose so a test that conflated them would fail here.
        assert_ne!(manifest.seq, manifest.build);
    }

    #[test]
    fn a_signature_from_an_untrusted_key_is_refused() {
        let refusal = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG_OTHER_KEY.as_bytes())
            .expect_err("that key is not in the list");
        assert!(matches!(refusal, Refusal::NotSignedByUs(_)), "got {refusal:?}");
    }

    #[test]
    fn a_legacy_signature_is_refused() {
        let refusal =
            verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG_LEGACY_ALGORITHM.as_bytes())
                .expect_err("allow_legacy is false");
        assert!(
            matches!(refusal, Refusal::NotSignedByUs(_) | Refusal::MalformedSignature(_)),
            "got {refusal:?}"
        );
    }

    #[test]
    fn one_flipped_byte_in_the_manifest_is_refused() {
        let tampered = BODY.replace("build = 1018", "build = 1019");
        let refusal = verify_with(&[(0, TEST_PUB)], tampered.as_bytes(), SIG.as_bytes())
            .expect_err("the signature covers the body");
        assert!(matches!(refusal, Refusal::NotSignedByUs(_)), "got {refusal:?}");
    }

    /// The key is chosen by trying the list, so a manifest signed by the standby
    /// verifies as epoch 1 even though it sits at index 1 -- and would still do
    /// so if epoch 0 were later dropped from the list.
    #[test]
    fn the_epoch_comes_from_the_key_that_verified_not_from_its_position() {
        // The test key is registered at epoch 4, at index 1. Verification must
        // report 4, and the manifest's own `key_epoch = 0` must then disagree.
        let refusal =
            verify_with(&[(3, OTHER_PUB), (4, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes())
                .expect_err("the manifest declares epoch 0 but epoch 4 signed it");
        assert_eq!(refusal, Refusal::EpochDisagrees { declared: 0, signed_by: 4 });
    }

    #[test]
    fn a_duplicated_key_is_refused_rather_than_last_wins() {
        let doubled = format!("{BODY}build = 1019\n");
        let refusal = parse_manifest(&doubled, 0).expect_err("two build lines");
        assert!(
            matches!(&refusal, Refusal::BadField(why) if why.contains("twice")),
            "got {refusal:?}"
        );
    }

    #[test]
    fn unknown_keys_are_ignored_so_the_format_can_grow() {
        let extended = format!("{BODY}display_version = 0.2.0\nsomething_from_2027 = yes\n");
        let manifest = parse_manifest(&extended, 0).expect("unknown keys must not be fatal");
        assert_eq!(manifest.build, 1018);
    }

    #[test]
    fn every_required_field_is_named_when_it_is_missing() {
        for field in ["seq", "build", "key_epoch", "minimum_build", "requires_reinstall"] {
            let without: String =
                BODY.lines().filter(|l| !l.starts_with(field)).collect::<Vec<_>>().join("\n");
            let refusal = parse_manifest(&without, 0)
                .expect_err("a missing required field must refuse, not default");
            // The message has to name the field. A generic "malformed manifest"
            // is what turns a release-night typo into an hour of guessing.
            assert!(
                matches!(&refusal, Refusal::BadField(why) if why.contains(field)),
                "removing `{field}` gave {refusal:?}, which does not name it"
            );
        }
    }

    #[test]
    fn a_non_numeric_ordinal_is_refused_rather_than_defaulted() {
        let bad = BODY.replace("seq = 7", "seq = banana");
        let refusal = parse_manifest(&bad, 0).expect_err("banana is not a number");
        assert!(
            matches!(&refusal, Refusal::BadField(why) if why.contains("seq")),
            "got {refusal:?}"
        );
    }

    #[test]
    fn an_absent_requires_reinstall_is_refused_not_assumed_false() {
        let without: String = BODY
            .lines()
            .filter(|l| !l.starts_with("requires_reinstall"))
            .collect::<Vec<_>>()
            .join("\n");
        let refusal = parse_manifest(&without, 0).expect_err("it is required, not optional");
        assert!(
            matches!(&refusal, Refusal::BadField(why) if why.contains("requires_reinstall")),
            "got {refusal:?}"
        );
    }

    /// The compiled-in prefix only bounds anything if the name cannot climb out
    /// of it.
    #[test]
    fn a_payload_name_that_is_not_a_plain_filename_is_refused() {
        for bad in [
            "../../etc/passwd",
            "sub/dir/file",
            "sub\\dir\\file",
            "..",
            "a..b",
            "https://evil.example/x",
            "file name with spaces",
            "",
        ] {
            assert!(!valid_payload_name(bad), "{bad:?} should be refused");
        }
        for good in ["brokkrsculpt-1018-linux-x86_64", "brokkrsculpt-1018-windows-x86_64.exe"] {
            assert!(valid_payload_name(good), "{good:?} should be allowed");
        }
    }

    #[test]
    fn a_manifest_naming_a_traversing_payload_is_refused() {
        let bad = BODY.replace(
            "linux-x86_64.name = brokkrsculpt-1018-linux-x86_64",
            "linux-x86_64.name = ../../../home/thomash/.bashrc",
        );
        // Only meaningful on the platform whose block was rewritten.
        if platform_slug() == Some("linux-x86_64") {
            let refusal = parse_manifest(&bad, 0).expect_err("that is not a filename");
            assert!(
                matches!(&refusal, Refusal::BadField(why) if why.contains("plain filename")),
                "got {refusal:?}"
            );
        }
    }

    #[test]
    fn a_sha256_that_is_not_64_hex_digits_is_refused() {
        if platform_slug() != Some("linux-x86_64") {
            return;
        }
        for bad in ["cafe", &"z".repeat(64), &"a".repeat(63)] {
            let text = BODY.replace(&"0".repeat(64), bad);
            let refusal = parse_manifest(&text, 0).expect_err("{bad} is not a digest");
            assert!(
                matches!(&refusal, Refusal::BadField(why) if why.contains("sha256")),
                "got {refusal:?} for {bad}"
            );
        }
    }

    #[test]
    fn a_manifest_at_or_below_the_floor_is_refused_and_a_newer_one_is_not() {
        let manifest = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes()).unwrap();
        // seq is 7.
        assert_eq!(
            admissible(&manifest, Floor { epoch: 0, seq: 7 }),
            Err(Refusal::BelowFloor { seq: 7, floor: 7 }),
            "equal is not newer"
        );
        assert_eq!(
            admissible(&manifest, Floor { epoch: 0, seq: 9 }),
            Err(Refusal::BelowFloor { seq: 7, floor: 9 })
        );
        assert_eq!(admissible(&manifest, Floor { epoch: 0, seq: 6 }), Ok(()));
        // A fresh install seeds zero and therefore has no floor at all.
        assert_eq!(admissible(&manifest, Floor::default()), Ok(()));
    }

    #[test]
    fn a_key_epoch_below_the_floor_is_refused_and_a_higher_one_clears_the_seq_floor() {
        let manifest = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes()).unwrap();
        assert_eq!(
            admissible(&manifest, Floor { epoch: 1, seq: 0 }),
            Err(Refusal::EpochBelowFloor { epoch: 0, floor: 1 }),
            "a superseded key must never be accepted again"
        );
        // A HIGHER epoch than the floor is a rotation: the seq floor no longer
        // applies, which is what stops a poisoned floor orphaning an install.
        let mut rotated = manifest.clone();
        rotated.key_epoch = 2;
        rotated.seq = 1;
        assert_eq!(
            admissible(&rotated, Floor { epoch: 0, seq: 999 }),
            Ok(()),
            "the recovery build must be acceptable however high the poisoned floor is"
        );
    }

    #[test]
    fn an_implausible_seq_is_refused() {
        let text = BODY.replace("seq = 7", &format!("seq = {}", MAX_SEQ + 1));
        // Parsing alone does not enforce it; the check lives in the verify path.
        let parsed = parse_manifest(&text, 0).unwrap();
        assert!(parsed.seq > MAX_SEQ);
    }

    #[test]
    fn minimum_build_is_strictly_below_so_a_client_at_the_minimum_is_left_alone() {
        let manifest = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes()).unwrap();
        // minimum_build is 1012.
        assert!(below_minimum(&manifest, 1011), "below the floor warns");
        assert!(!below_minimum(&manifest, 1012), "AT the minimum meets it");
        assert!(!below_minimum(&manifest, 1013), "above it is fine");
    }

    #[test]
    fn an_oversized_manifest_is_refused_before_anything_is_trusted() {
        let huge = vec![b'x'; (MAX_MANIFEST_BYTES + 1) as usize];
        let refusal = verify_manifest(&huge, SIG.as_bytes()).expect_err("over the cap");
        assert!(matches!(refusal, Refusal::TooLarge { .. }), "got {refusal:?}");

        let huge_sig = vec![b'x'; (MAX_SIGNATURE_BYTES + 1) as usize];
        let refusal = verify_manifest(BODY.as_bytes(), &huge_sig).expect_err("over the cap");
        assert!(matches!(refusal, Refusal::TooLarge { .. }), "got {refusal:?}");
    }

    #[test]
    fn a_manifest_with_too_many_lines_is_refused() {
        let many = "# comment\n".repeat(MAX_MANIFEST_LINES + 1);
        let refusal = parse_manifest(&many, 0).expect_err("over the line cap");
        assert!(
            matches!(&refusal, Refusal::BadField(why) if why.contains("lines")),
            "got {refusal:?}"
        );
    }

    /// The production entry point must refuse the production fixtures too --
    /// this is the one test that exercises `verify_manifest` itself rather than
    /// the test harness, proving the shipped key list does not accept a manifest
    /// signed by a throwaway key.
    #[test]
    fn the_shipped_keys_do_not_accept_the_test_fixture() {
        let refusal = verify_manifest(BODY.as_bytes(), SIG.as_bytes())
            .expect_err("the test key must not be trusted by a release build");
        assert!(matches!(refusal, Refusal::NotSignedByUs(_)), "got {refusal:?}");
    }

    #[test]
    fn the_urls_are_release_assets_rather_than_the_rate_limited_api() {
        for url in [MANIFEST_URL, SIGNATURE_URL, DOWNLOAD_PREFIX] {
            assert!(url.starts_with("https://"), "{url} must be https");
            assert!(!url.contains("api.github.com"), "{url} must not use the rate-limited API");
        }
        assert!(DOWNLOAD_PREFIX.ends_with('/'), "the prefix must end in a slash to bound names");
    }

    /// The redirect allowlist is the only thing standing between a 302 and an
    /// arbitrary host, so its edge cases get named tests rather than a glance.
    #[test]
    fn the_host_allowlist_admits_github_and_nothing_that_merely_looks_like_it() {
        for good in [
            "github.com",
            "release-assets.githubusercontent.com",
            "objects.githubusercontent.com",
            "GITHUB.COM",
        ] {
            assert!(host_is_allowed(good), "{good} should be allowed");
        }
        for bad in [
            // Ends with "github.com", which a bare suffix test would admit.
            "evilgithub.com",
            "notgithub.com",
            // Ends with "githubusercontent.com" without the dot.
            "evil-githubusercontent.com",
            "github.com.evil.example",
            "evil.example",
            "",
            // Non-ASCII, where a homograph could otherwise sneak through.
            "gіthub.com",
        ] {
            assert!(!host_is_allowed(bad), "{bad} should be refused");
        }
    }

    #[test]
    fn the_host_is_taken_from_the_authority_and_not_from_a_prefix() {
        assert_eq!(host_of("https://github.com/a/b"), Some("github.com"));
        assert_eq!(host_of("https://github.com"), Some("github.com"));
        assert_eq!(host_of("https://github.com:443/x"), Some("github.com"));
        assert_eq!(
            host_of("https://release-assets.githubusercontent.com/x?se=1"),
            Some("release-assets.githubusercontent.com")
        );
        // Userinfo is the classic trick: the real host here is evil.example.
        // Refused outright rather than parsed, so it can never be mistaken.
        assert_eq!(host_of("https://github.com@evil.example/x"), None);
        assert_eq!(host_of("http://github.com/x"), None, "https only");
        assert_eq!(host_of("https:///x"), None);
        assert_eq!(host_of("not a url"), None);
    }

    /// The tick writes a file the next launch reads. If those two disagree the
    /// switch silently does nothing, which is the worst way for a privacy
    /// control to fail.
    #[test]
    fn the_update_preference_survives_a_round_trip_through_its_own_file_format() {
        for when in [When::Never, When::Welcome, When::Always] {
            let written = Settings { when, skip_build: None };
            let read_back = settings_from(&settings_text(&written));
            assert_eq!(read_back.when, when, "{when:?} did not survive");
        }
        let with_skip = Settings { when: When::Always, skip_build: Some(1017) };
        let read_back = settings_from(&settings_text(&with_skip));
        assert_eq!(read_back, with_skip);

        // The comment lines the writer emits must not parse as settings: they
        // contain the words `never`, `welcome` and `always`.
        let text = settings_text(&Settings { when: When::Never, skip_build: None });
        assert_eq!(settings_from(&text).when, When::Never, "a comment was read as a value");
    }

    /// The packager kill switch has to stop the CHECK, not just hide the UI.
    /// A distro build that keeps polling GitHub to display nothing is a
    /// connection nobody asked for and nobody can see.
    #[test]
    fn the_packager_kill_switch_refuses_before_any_request() {
        let off = Settings { when: When::Never, skip_build: None };
        // `check` returns before touching the network for a `Never` setting --
        // and before that, for a build with no ordinal at all.
        assert_eq!(check(None, &off, Floor::default()), Err(Refusal::NotAReleaseBuild));
    }

    /// Build a payload description for some bytes, the way a real manifest
    /// would: the digest is over exactly those bytes.
    fn payload_for(bytes: &[u8]) -> Payload {
        let digest = ring::digest::digest(&ring::digest::SHA256, bytes);
        Payload {
            name: "brokkrsculpt-1018-linux-x86_64".to_string(),
            size: bytes.len() as u64,
            sha256: digest.as_ref().iter().map(|b| format!("{b:02x}")).collect(),
        }
    }

    #[test]
    fn a_payload_that_matches_its_signed_size_and_digest_is_accepted() {
        let bytes = b"a plausible executable, for the purposes of a digest".repeat(500);
        let payload = payload_for(&bytes);
        let mut sink = Vec::new();
        assert_eq!(check_payload(&bytes[..], &payload, &mut sink), Ok(()));
        // What was verified is what landed.
        assert_eq!(sink, bytes);
    }

    #[test]
    fn one_flipped_byte_in_the_payload_is_refused() {
        let bytes = b"a plausible executable".repeat(100);
        let payload = payload_for(&bytes);
        let mut tampered = bytes.clone();
        tampered[500] ^= 0x01;
        let mut sink = Vec::new();
        let refusal = check_payload(&tampered[..], &payload, &mut sink).expect_err("one bit");
        assert!(matches!(refusal, Refusal::DigestMismatch { .. }), "got {refusal:?}");
    }

    /// A truncated download must be named as one rather than reported as a
    /// digest mismatch, which reads like tampering.
    #[test]
    fn a_truncated_payload_is_refused_as_a_length_and_not_as_a_digest() {
        let bytes = b"a plausible executable".repeat(100);
        let payload = payload_for(&bytes);
        let mut sink = Vec::new();
        let refusal =
            check_payload(&bytes[..bytes.len() - 10], &payload, &mut sink).expect_err("short");
        assert!(
            matches!(refusal, Refusal::PayloadSizeMismatch { declared, actual }
                if declared == bytes.len() as u64 && actual == bytes.len() as u64 - 10),
            "got {refusal:?}"
        );
    }

    #[test]
    fn a_payload_longer_than_declared_is_refused_without_buffering_all_of_it() {
        let bytes = b"a plausible executable".repeat(100);
        let mut payload = payload_for(&bytes);
        payload.size = 50; // the manifest says far less than arrives
        let mut sink = Vec::new();
        let refusal = check_payload(&bytes[..], &payload, &mut sink).expect_err("too long");
        assert!(matches!(refusal, Refusal::PayloadSizeMismatch { .. }), "got {refusal:?}");
    }

    /// The signed size is a secondary tightening. The compiled-in ceiling is
    /// what stops someone who can answer the request from streaming gigabytes
    /// into the user's directory before any check fails.
    #[test]
    fn a_declared_size_over_the_absolute_cap_is_refused_before_reading_anything() {
        let payload = Payload {
            name: "brokkrsculpt-1018-linux-x86_64".to_string(),
            size: MAX_UPDATE_BYTES + 1,
            sha256: "0".repeat(64),
        };
        // An empty reader: if the cap were not checked first this would fail on
        // the length instead, which would mean the cap was never consulted.
        let mut sink = Vec::new();
        let refusal = check_payload(&[][..], &payload, &mut sink).expect_err("over the ceiling");
        assert_eq!(refusal, Refusal::TooLarge { what: "update payload", cap: MAX_UPDATE_BYTES });
    }

    #[test]
    fn a_payload_url_can_only_ever_be_built_from_the_compiled_in_prefix() {
        let payload = payload_for(b"x");
        let url = payload_url(&payload);
        assert_eq!(url, format!("{DOWNLOAD_PREFIX}brokkrsculpt-1018-linux-x86_64"));
        assert!(host_is_allowed(host_of(&url).expect("an absolute https url")));
    }

    /// An offer with no payload for this platform is still worth showing --
    /// the build exists -- but accepting it cannot do anything, and that has to
    /// fail before a socket is opened rather than after.
    #[test]
    fn accepting_an_offer_with_no_payload_refuses_without_touching_the_network() {
        let offer = Offer {
            build: 1018,
            running: 1012,
            known_bad: false,
            requires_reinstall: false,
            payload: None,
            seq: 1,
            key_epoch: 0,
        };
        // The directory is irrelevant: an offer with no payload must refuse
        // before a socket is opened or a directory is created.
        assert_eq!(
            download(&offer, std::path::Path::new("/nonexistent")),
            Err(Refusal::UnsupportedPlatform)
        );
    }

    /// The offer carries the payload from the manifest that was verified, so
    /// accepting it cannot pick up a different manifest's bytes.
    #[test]
    fn the_offer_carries_the_payload_from_the_manifest_that_was_verified() {
        let manifest = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes()).unwrap();
        if platform_slug() == Some("linux-x86_64") {
            let payload = manifest.payload.expect("the fixture names a linux payload");
            assert_eq!(payload.name, "brokkrsculpt-1018-linux-x86_64");
            assert_eq!(payload.size, 33543336);
            // And the URL for it can only come from the compiled-in prefix.
            assert!(payload_url(&payload).starts_with(DOWNLOAD_PREFIX));
        }
    }

    /// **The only clock value this design stores, and it must never refuse
    /// anything.** That is the whole difference from the `expires` field the
    /// plan rejected: a wrong clock costs a sentence in the Help panel, not the
    /// ability to update.
    #[test]
    fn freshness_is_reported_and_never_enforced() {
        let day = 86_400;
        assert_eq!(days_since_check("last_check = 1000", 1000 + day), Some(1));
        assert_eq!(days_since_check("last_check = 1000", 1000 + 10 * day), Some(10));
        assert_eq!(days_since_check("last_check = 1000", 1000), Some(0));
        // Never recorded.
        assert_eq!(days_since_check("", 1000), None);
        assert_eq!(days_since_check("last_check = banana", 1000), None);
        // A clock that went backwards -- a fresh VM before NTP, a dead CMOS
        // battery -- reads as unknown rather than as a negative age, and above
        // all does not panic on the subtraction.
        assert_eq!(days_since_check("last_check = 9999", 1000), None);
    }

    /// `update.state` is rewritten whole, so a field written by one call must
    /// survive the next. Otherwise the revert loses the digest it needs.
    #[test]
    fn rewriting_one_state_field_preserves_the_others() {
        let text = "floor_epoch = 1\nfloor_seq = 7\nprevious_sha256 = abc\ninstalled_build = 1018\nlast_check = 500\n";
        assert_eq!(previous_sha256_from(text).as_deref(), Some("abc"));
        assert_eq!(floor_from(text), Floor { epoch: 1, seq: 7 });
        assert_eq!(days_since_check(text, 500 + 86_400), Some(1));
    }

    /// Every bug report should say what the updater is doing, because "it
    /// stopped updating" is otherwise a conversation rather than a diagnosis.
    #[test]
    fn the_diagnostics_line_names_the_setting_and_the_freshness() {
        let line = outcome_line();
        assert!(
            ["off", "on", "welcome"].iter().any(|state| line.contains(state)),
            "it must say whether checking is on: {line}"
        );
        assert!(line.contains("update check") || line.contains("checked"), "got {line}");
        // It must never be empty, because an empty field in a bug report reads
        // as "not applicable" rather than as "nobody wrote this".
        assert!(!line.trim().is_empty());
    }

    /// **The end the signer writes, parsed by the end the client runs.**
    ///
    /// Every other test here feeds `parse_manifest` a fixture this file wrote.
    /// That proves the parser self-consistent and nothing about whether
    /// `scripts/sign-release.sh` emits something it will accept -- and those are
    /// two programs, in two languages, agreeing by convention alone. This
    /// fixture is the script's real output, captured 2026-08-30 by running it
    /// against a stubbed `gh` at a deliberate worst case: six-digit ordinals,
    /// all three platforms, `requires_reinstall = 1`, a `minimum_build` floor.
    /// Only the digests are substituted, because the stub's payload bytes are
    /// not interesting and a real one would go stale.
    ///
    /// If the script's layout ever drifts -- a separator, a field order, a
    /// renamed key -- this is what fails, here, rather than on release night
    /// with every client silently refusing the manifest.
    #[test]
    fn the_signing_scripts_own_output_parses() {
        let emitted = format!(
            "seq = 7\n\
             build = 999999\n\
             key_epoch = 0\n\
             minimum_build = 998877\n\
             requires_reinstall = 1\n\
             linux-x86_64.name = brokkrsculpt-999999-linux-x86_64\n\
             linux-x86_64.size = 64\n\
             linux-x86_64.sha256 = {d}\n\
             windows-x86_64.name = brokkrsculpt-999999-windows-x86_64.exe\n\
             windows-x86_64.size = 70\n\
             windows-x86_64.sha256 = {d}\n\
             macos-arm64.name = brokkrsculpt-999999-macos-arm64.zip\n\
             macos-arm64.size = 67\n\
             macos-arm64.sha256 = {d}\n",
            d = "a".repeat(64)
        );
        let manifest = parse_manifest(&emitted, 0).expect("the signer's own output must parse");
        assert_eq!(manifest.seq, 7);
        assert_eq!(manifest.build, 999_999);
        assert_eq!(manifest.minimum_build, 998_877);
        assert!(manifest.requires_reinstall, "the flag must survive the round trip");
        // Two different number spaces, kept different in the real output.
        assert_ne!(manifest.seq, manifest.build);
        // Whichever platform this test runs on, its block must be the one read.
        if let Some(slug) = platform_slug() {
            let payload = manifest.payload.expect("this platform is in the manifest");
            assert!(payload.name.starts_with("brokkrsculpt-999999-"), "got {}", payload.name);
            assert!(payload.name.contains(slug), "{} should name {slug}", payload.name);
            assert!(valid_payload_name(&payload.name));
        }
        // And it is comfortably inside every cap the client enforces, at an
        // ordinal far larger than anything real.
        assert!(emitted.len() as u64 <= MAX_MANIFEST_BYTES);
        assert!(emitted.lines().count() <= MAX_MANIFEST_LINES);
        assert!(emitted.lines().all(|line| line.len() <= MAX_FIELD_BYTES));
        assert!(!emitted.contains('#'), "a `#` in a value would break the number parse");
    }

    /// **The production keys, proven against real signatures they made.**
    ///
    /// Every other test here uses a throwaway key, which proves the algorithm
    /// and nothing about the two constants at the top of this file. If either
    /// public key were mistranscribed -- one character, in a base64 blob nobody
    /// reads -- everything would still compile, every other test would still
    /// pass, and every installed copy would refuse every release for ever,
    /// through the exact channel the fix would have to travel down. It is the
    /// one failure in this design with no recovery path.
    ///
    /// So: two manifests signed on 2026-08-30 with the real secret halves, and
    /// checked here through `verify_manifest` -- the production entry point,
    /// against `TRUSTED_KEYS` as compiled. `minisign -V` passing proves only
    /// that the `.pub` FILES match; this proves the binary does.
    ///
    /// The epoch 1 signature additionally comes from the RESTORED backup rather
    /// than the original, so this doubles as the standby's restore drill.
    #[test]
    fn the_compiled_in_keys_accept_manifests_the_real_secret_halves_signed() {
        let body = |epoch: u32| {
            format!(
                "seq = 1\nbuild = 1005\nkey_epoch = {epoch}\nminimum_build = 0\n\
                 requires_reinstall = 0\n\
                 linux-x86_64.name = brokkrsculpt-1005-linux-x86_64\n\
                 linux-x86_64.size = 33543336\n\
                 linux-x86_64.sha256 = {}\n",
                "1".repeat(64)
            )
        };
        const SIG_EPOCH0: &str = "untrusted comment: signature from minisign secret key\nRURMzxH8+lnQtvUIc7Bh4jWYiMPTYr9tr/fpfjQz9dPbM421l4QwQtWR+RRLuxaWlqarg9qAJveooz3lBWf5Xd5jNUkSw8NAoA4=\ntrusted comment: timestamp:1788053461\tfile:keyproof.conf\thashed\nwStbyW/pP1tGX6E9xY5oSNqymfRt7Mc375bEfKyCOpyCXsrGuUlNnaIF7x3cYpjyVBbjzkS8mxBcJJaKfevGAg==\n";
        const SIG_EPOCH1: &str = "untrusted comment: signature from minisign secret key\nRUT9wJerF4yzvU3v29yVaSGkhBqRG5AZz5lNR7xGiHTqupiC6MbDbFzhw5JpB42OAFA6cE9edx9iZI20x0R+2a45Gqf0d+jfwQw=\ntrusted comment: timestamp:1788053470\tfile:keyproof-epoch1.conf\thashed\nUJbBsg1CVeyslgN1uvl/ZIfd1qq1CcuM1qRog+PnQPf2fsbYVsapNmBNhtRAsxgUkC6fDoNV2zC7JpEXrrSKAQ==\n";

        // The live key.
        let live = verify_manifest(body(0).as_bytes(), SIG_EPOCH0.as_bytes())
            .expect("TRUSTED_KEYS[0] must accept what the epoch 0 secret half signed");
        assert_eq!(live.key_epoch, 0);
        assert_eq!(live.build, 1005);

        // The standby, signed by the copy restored from backup.
        let standby = verify_manifest(body(1).as_bytes(), SIG_EPOCH1.as_bytes())
            .expect("TRUSTED_KEYS[1] must accept what the restored epoch 1 key signed");
        assert_eq!(standby.key_epoch, 1);

        // A signature does not travel between manifests: the epoch 1 signature
        // over the epoch 0 body must fail, or the anti-rollback floor could be
        // fed a body its signature never covered.
        assert!(
            verify_manifest(body(0).as_bytes(), SIG_EPOCH1.as_bytes()).is_err(),
            "a signature must not verify against a body it did not sign"
        );
    }

    /// **The floor must rise on a successful apply, and only then.**
    ///
    /// Found by running the first real update on this machine: it installed
    /// correctly and left `floor_seq = 0`, so the install would have accepted an
    /// older manifest afterwards. Nothing in the suite caught it because every
    /// other test drives the pure functions rather than the apply path — which
    /// is exactly why the hop was worth doing by hand.
    #[test]
    fn a_successful_apply_raises_the_floor_and_names_what_it_installed() {
        // The state file is per-install and this test must not write the real
        // one, so the shape is asserted through the parsers that read it.
        let after =
            "floor_epoch = 0\nfloor_seq = 7\ninstalled_build = 1019\nprevious_sha256 = abc\n";
        assert_eq!(floor_from(after), Floor { epoch: 0, seq: 7 }, "the floor must be the seq");
        assert_eq!(
            previous_sha256_from(after).as_deref(),
            Some("abc"),
            "the revert digest survives"
        );

        // And a manifest at or below that floor is then refused, which is the
        // whole point of raising it.
        let manifest = verify_with(&[(0, TEST_PUB)], BODY.as_bytes(), SIG.as_bytes()).unwrap();
        assert_eq!(manifest.seq, 7);
        assert_eq!(
            admissible(&manifest, floor_from(after)),
            Err(Refusal::BelowFloor { seq: 7, floor: 7 })
        );
    }

    /// CI runs `--version | grep -qx "build = $BROKKR_BUILD"`. If this shape
    /// changes, the release pipeline stops verifying the stamp and starts
    /// failing every build -- or worse, keeps passing while checking nothing.
    #[test]
    fn the_version_report_is_the_shape_ci_greps_for() {
        let report = version_report();
        let fields: Vec<(&str, &str)> = crate::paths::entries(&report).collect();
        let keys: Vec<&str> = fields.iter().map(|(k, _)| *k).collect();
        assert_eq!(keys, vec!["version", "build", "commit"], "got {report:?}");

        let build = fields.iter().find(|(k, _)| *k == "build").unwrap().1;
        match crate::app::build_number() {
            // The printed ordinal must BE the ordinal, not a copy that can drift.
            Some(n) => assert_eq!(build, n.to_string(), "the printed ordinal disagrees"),
            // Never `0`: `grep -qx "build = 0"` must not succeed on a build that
            // was never stamped.
            None => assert_eq!(build, "none"),
        }
        assert!(report.ends_with('\n'), "grep -x needs a terminated final line");
    }

    #[test]
    fn the_settings_default_to_checking_always_and_survive_a_broken_file() {
        assert_eq!(Settings::default().when, When::Always, "settled 2026-08-30");
        assert_eq!(settings_from("check_for_updates = never").when, When::Never);
        assert_eq!(settings_from("check_for_updates = welcome").when, When::Welcome);
        assert_eq!(settings_from("check_for_updates = always").when, When::Always);
        // An unreadable value keeps the default rather than refusing to launch:
        // this is the user's own file, not attacker bytes.
        assert_eq!(settings_from("check_for_updates = banana").when, When::Always);
        assert_eq!(settings_from("skip_build = 1017").skip_build, Some(1017));
        assert_eq!(settings_from("skip_build = banana").skip_build, None);
        assert_eq!(settings_from("").skip_build, None);
    }

    /// The documented reset is "delete `update.state`", so every unreadable
    /// state must land on a zero floor rather than on a refusal -- the user
    /// performing that reset has no terminal to read an error in.
    #[test]
    fn a_missing_or_broken_state_file_means_no_floor_rather_than_a_refusal() {
        assert_eq!(floor_from(""), Floor { epoch: 0, seq: 0 });
        assert_eq!(floor_from("floor_epoch = 1\nfloor_seq = 42"), Floor { epoch: 1, seq: 42 });
        assert_eq!(floor_from("floor_seq = banana"), Floor::default());
        assert_eq!(floor_from("garbage\n\n#comment"), Floor::default());
    }

    /// `skip_build` answers an offer. It does not answer "the build you are on
    /// is known broken", and conflating the two would silence the one message
    /// that matters most.
    #[test]
    fn the_offer_wording_never_claims_a_direction_it_does_not_have() {
        let up = Offer {
            build: 1018,
            running: 1012,
            known_bad: false,
            requires_reinstall: false,
            payload: None,
            seq: 1,
            key_epoch: 0,
        };
        assert!(up.headline().contains("1018"));
        assert!(up.headline().starts_with("Build 1018 is out"));

        // A rollback offers a LOWER ordinal. It must not read as an upgrade.
        let down = Offer {
            build: 1012,
            running: 1018,
            known_bad: false,
            requires_reinstall: false,
            payload: None,
            seq: 1,
            key_epoch: 0,
        };
        assert!(!down.headline().contains("is out"), "got {:?}", down.headline());

        let bad = Offer {
            build: 1031,
            running: 1012,
            known_bad: true,
            requires_reinstall: false,
            payload: None,
            seq: 1,
            key_epoch: 0,
        };
        assert!(bad.headline().contains("known problem"));
        assert!(bad.headline().contains("1012") && bad.headline().contains("1031"));
    }
}
